INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AFG', 'Afghanistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AHO', 'Curacao', 'Netherlands Antilles');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ALB', 'Albania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ALG', 'Algeria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AND', 'Andorra', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANG', 'Angola', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANT', 'Antigua', 'Antigua and Barbuda');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANZ', 'Australia', 'Australasia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARG', 'Argentina', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARM', 'Armenia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARU', 'Aruba', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ASA', 'American Samoa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AUS', 'Australia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AUT', 'Austria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AZE', 'Azerbaijan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAH', 'Bahamas', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAN', 'Bangladesh', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAR', 'Barbados', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BDI', 'Burundi', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BEL', 'Belgium', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BEN', 'Benin', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BER', 'Bermuda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BHU', 'Bhutan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BIH', 'Bosnia and Herzegovina', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BIZ', 'Belize', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BLR', 'Belarus', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOH', 'Czech Republic', 'Bohemia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOL', 'Boliva', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOT', 'Botswana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRA', 'Brazil', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRN', 'Bahrain', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRU', 'Brunei', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BUL', 'Bulgaria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BUR', 'Burkina Faso', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAF', 'Central African Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAM', 'Cambodia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAN', 'Canada', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAY', 'Cayman Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CGO', 'Republic of Congo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHA', 'Chad', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHI', 'Chile', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHN', 'China', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CIV', 'Ivory Coast', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CMR', 'Cameroon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COD', 'Democratic Republic of the Congo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COK', 'Cook Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COL', 'Colombia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COM', 'Comoros', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CPV', 'Cape Verde', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRC', 'Costa Rica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRO', 'Croatia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRT', 'Greece', 'Crete');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CUB', 'Cuba', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CYP', 'Cyprus', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CZE', 'Czech Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DEN', 'Denmark', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DJI', 'Djibouti', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DMA', 'Dominica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DOM', 'Dominican Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ECU', 'Ecuador', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EGY', 'Egypt', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ERI', 'Eritrea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ESA', 'El Salvador', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ESP', 'Spain', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EST', 'Estonia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ETH', 'Ethiopia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EUN', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FIJ', 'Fiji', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FIN', 'Finland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FRA', 'France', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FRG', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FSM', 'Micronesia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GAB', 'Gabon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GAM', 'Gambia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GBR', 'UK', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GBS', 'Guinea-Bissau', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GDR', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GEO', 'Georgia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GEQ', 'Equatorial Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GER', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GHA', 'Ghana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GRE', 'Greece', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GRN', 'Grenada', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUA', 'Guatemala', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUI', 'Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUM', 'Guam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUY', 'Guyana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HAI', 'Haiti', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HKG', 'China', 'Hong Kong');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HON', 'Honduras', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HUN', 'Hungary', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('INA', 'Indonesia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IND', 'India', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IOA', 'Individual Olympic Athletes', 'Individual Olympic Athletes');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRI', 'Iran', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRL', 'Ireland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRQ', 'Iraq', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISL', 'Iceland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISR', 'Israel', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISV', 'Virgin Islands, US', 'Virgin Islands');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ITA', 'Italy', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IVB', 'Virgin Islands, British', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JAM', 'Jamaica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JOR', 'Jordan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JPN', 'Japan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KAZ', 'Kazakhstan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KEN', 'Kenya', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KGZ', 'Kyrgyzstan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KIR', 'Kiribati', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KOR', 'South Korea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KOS', 'Kosovo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KSA', 'Saudi Arabia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KUW', 'Kuwait', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LAO', 'Laos', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LAT', 'Latvia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LBA', 'Libya', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LBR', 'Liberia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LCA', 'Saint Lucia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LES', 'Lesotho', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LIB', 'Lebanon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LIE', 'Liechtenstein', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LTU', 'Lithuania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LUX', 'Luxembourg', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAD', 'Madagascar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAL', 'Malaysia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAR', 'Morocco', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAS', 'Malaysia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAW', 'Malawi', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MDA', 'Moldova', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MDV', 'Maldives', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MEX', 'Mexico', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MGL', 'Mongolia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MHL', 'Marshall Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MKD', 'Macedonia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MLI', 'Mali', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MLT', 'Malta', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MNE', 'Montenegro', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MON', 'Monaco', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MOZ', 'Mozambique', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MRI', 'Mauritius', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MTN', 'Mauritania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MYA', 'Myanmar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NAM', 'Namibia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NBO', 'Malaysia', 'North Borneo');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NCA', 'Nicaragua', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NED', 'Netherlands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NEP', 'Nepal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NFL', 'Canada', 'Newfoundland');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NGR', 'Nigeria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NIG', 'Niger', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NOR', 'Norway', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NRU', 'Nauru', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NZL', 'New Zealand', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('OMA', 'Oman', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAK', 'Pakistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAN', 'Panama', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAR', 'Paraguay', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PER', 'Peru', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PHI', 'Philippines', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PLE', 'Palestine', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PLW', 'Palau', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PNG', 'Papua New Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('POL', 'Poland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('POR', 'Portugal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PRK', 'North Korea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PUR', 'Puerto Rico', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('QAT', 'Qatar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RHO', 'Zimbabwe', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ROT', 'nan', 'Refugee Olympic Team');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ROU', 'Romania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RSA', 'South Africa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RUS', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RWA', 'Rwanda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SAA', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SAM', 'Samoa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SCG', 'Serbia', 'Serbia and Montenegro');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SEN', 'Senegal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SEY', 'Seychelles', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SIN', 'Singapore', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SKN', 'Saint Kitts', 'Turks and Caicos Islands');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SLE', 'Sierra Leone', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SLO', 'Slovenia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SMR', 'San Marino', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SOL', 'Solomon Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SOM', 'Somalia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SRB', 'Serbia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SRI', 'Sri Lanka', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SSD', 'South Sudan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('STP', 'Sao Tome and Principe', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUD', 'Sudan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUI', 'Switzerland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUR', 'Suriname', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SVK', 'Slovakia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SWE', 'Sweden', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SWZ', 'Swaziland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SYR', 'Syria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TAN', 'Tanzania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TCH', 'Czech Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TGA', 'Tonga', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('THA', 'Thailand', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TJK', 'Tajikistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TKM', 'Turkmenistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TLS', 'Timor-Leste', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TOG', 'Togo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TPE', 'Taiwan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TTO', 'Trinidad', 'Trinidad and Tobago');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUN', 'Tunisia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUR', 'Turkey', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUV', 'nan', 'Tuvalu');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UAE', 'United Arab Emirates', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UAR', 'Syria', 'United Arab Republic');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UGA', 'Uganda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UKR', 'Ukraine', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UNK', 'nan', 'Unknown');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('URS', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('URU', 'Uruguay', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('USA', 'USA', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UZB', 'Uzbekistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VAN', 'Vanuatu', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VEN', 'Venezuela', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VIE', 'Vietnam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VIN', 'Saint Vincent', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VNM', 'Vietnam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('WIF', 'Trinidad', 'West Indies Federation');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YAR', 'Yemen', 'North Yemen');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YEM', 'Yemen', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YMD', 'Yemen', 'South Yemen');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YUG', 'Serbia', 'Yugoslavia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ZAM', 'Zambia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ZIM', 'Zimbabwe', '');

COMMIT;
