INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (1, 'Aeronautics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (2, 'Alpine Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (3, 'Alpinism');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (4, 'Archery');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (5, 'Art Competitions');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (6, 'Athletics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (7, 'Badminton');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (8, 'Baseball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (9, 'Basketball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (10, 'Basque Pelota');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (11, 'Beach Volleyball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (12, 'Biathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (13, 'Bobsleigh');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (14, 'Boxing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (15, 'Canoeing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (16, 'Cricket');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (17, 'Croquet');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (18, 'Cross Country Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (19, 'Curling');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (20, 'Cycling');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (21, 'Diving');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (22, 'Equestrianism');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (23, 'Fencing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (24, 'Figure Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (25, 'Football');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (26, 'Freestyle Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (27, 'Golf');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (28, 'Gymnastics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (29, 'Handball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (30, 'Hockey');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (31, 'Ice Hockey');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (32, 'Jeu De Paume');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (33, 'Judo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (34, 'Lacrosse');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (35, 'Luge');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (36, 'Military Ski Patrol');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (37, 'Modern Pentathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (38, 'Motorboating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (39, 'Nordic Combined');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (40, 'Polo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (41, 'Racquets');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (42, 'Rhythmic Gymnastics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (43, 'Roque');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (44, 'Rowing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (45, 'Rugby');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (46, 'Rugby Sevens');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (47, 'Sailing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (48, 'Shooting');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (49, 'Short Track Speed Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (50, 'Skeleton');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (51, 'Ski Jumping');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (52, 'Snowboarding');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (53, 'Softball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (54, 'Speed Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (55, 'Swimming');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (56, 'Synchronized Swimming');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (57, 'Table Tennis');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (58, 'Taekwondo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (59, 'Tennis');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (60, 'Trampolining');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (61, 'Triathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (62, 'Tug-Of-War');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (63, 'Volleyball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (64, 'Water Polo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (65, 'Weightlifting');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (66, 'Wrestling');

COMMIT;
