INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (1, 1, 'Aeronautics Mixed Aeronautics');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (2, 2, 'Alpine Skiing Men''s Combined');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (3, 2, 'Alpine Skiing Men''s Downhill');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (4, 2, 'Alpine Skiing Men''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (5, 2, 'Alpine Skiing Men''s Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (6, 2, 'Alpine Skiing Men''s Super G');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (7, 2, 'Alpine Skiing Women''s Combined');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (8, 2, 'Alpine Skiing Women''s Downhill');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (9, 2, 'Alpine Skiing Women''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (10, 2, 'Alpine Skiing Women''s Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (11, 2, 'Alpine Skiing Women''s Super G');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (12, 3, 'Alpinism Mixed Alpinism');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (13, 4, 'Archery Men''s Au Chapelet, 33 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (14, 4, 'Archery Men''s Au Chapelet, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (15, 4, 'Archery Men''s Au Cordon Dore, 33 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (16, 4, 'Archery Men''s Au Cordon Dore, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (17, 4, 'Archery Men''s Championnat Du Monde');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (18, 4, 'Archery Men''s Continental Style');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (19, 4, 'Archery Men''s Double American Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (20, 4, 'Archery Men''s Double York Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (21, 4, 'Archery Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (22, 4, 'Archery Men''s Pole Archery, Large Birds, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (23, 4, 'Archery Men''s Pole Archery, Large Birds, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (24, 4, 'Archery Men''s Pole Archery, Small Birds, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (25, 4, 'Archery Men''s Pole Archery, Small Birds, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (26, 4, 'Archery Men''s Sur La Perche a La Herse');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (27, 4, 'Archery Men''s Sur La Perche a La Pyramide');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (28, 4, 'Archery Men''s Target Archery, 28 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (29, 4, 'Archery Men''s Target Archery, 28 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (30, 4, 'Archery Men''s Target Archery, 33 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (31, 4, 'Archery Men''s Target Archery, 33 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (32, 4, 'Archery Men''s Target Archery, 50 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (33, 4, 'Archery Men''s Target Archery, 50 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (34, 4, 'Archery Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (35, 4, 'Archery Men''s Team Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (36, 4, 'Archery Men''s Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (37, 4, 'Archery Women''s Double Columbia Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (38, 4, 'Archery Women''s Double National Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (39, 4, 'Archery Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (40, 4, 'Archery Women''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (41, 4, 'Archery Women''s Team Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (42, 5, 'Art Competitions Mixed Architecture');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (43, 5, 'Art Competitions Mixed Architecture, Architectural Designs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (44, 5, 'Art Competitions Mixed Architecture, Designs For Town Planning');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (45, 5, 'Art Competitions Mixed Architecture, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (46, 5, 'Art Competitions Mixed Literature');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (47, 5, 'Art Competitions Mixed Literature, Dramatic Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (48, 5, 'Art Competitions Mixed Literature, Epic Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (49, 5, 'Art Competitions Mixed Literature, Lyric Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (50, 5, 'Art Competitions Mixed Literature, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (51, 5, 'Art Competitions Mixed Music');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (52, 5, 'Art Competitions Mixed Music, Compositions For Orchestra');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (53, 5, 'Art Competitions Mixed Music, Compositions For Solo Or Chorus');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (54, 5, 'Art Competitions Mixed Music, Instrumental And Chamber');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (55, 5, 'Art Competitions Mixed Music, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (56, 5, 'Art Competitions Mixed Music, Vocals');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (57, 5, 'Art Competitions Mixed Painting');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (58, 5, 'Art Competitions Mixed Painting, Applied Arts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (59, 5, 'Art Competitions Mixed Painting, Drawings And Water Colors');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (60, 5, 'Art Competitions Mixed Painting, Graphic Arts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (61, 5, 'Art Competitions Mixed Painting, Paintings');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (62, 5, 'Art Competitions Mixed Painting, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (63, 5, 'Art Competitions Mixed Sculpturing');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (64, 5, 'Art Competitions Mixed Sculpturing, Medals');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (65, 5, 'Art Competitions Mixed Sculpturing, Medals And Plaques');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (66, 5, 'Art Competitions Mixed Sculpturing, Medals And Reliefs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (67, 5, 'Art Competitions Mixed Sculpturing, Reliefs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (68, 5, 'Art Competitions Mixed Sculpturing, Statues');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (69, 5, 'Art Competitions Mixed Sculpturing, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (70, 5, 'Art Competitions Mixed Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (71, 6, 'Athletics Men''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (72, 6, 'Athletics Men''s 1,500 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (73, 6, 'Athletics Men''s 1,600 metres Medley Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (74, 6, 'Athletics Men''s 10 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (75, 6, 'Athletics Men''s 10 mile Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (76, 6, 'Athletics Men''s 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (77, 6, 'Athletics Men''s 100 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (78, 6, 'Athletics Men''s 110 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (79, 6, 'Athletics Men''s 2,500 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (80, 6, 'Athletics Men''s 2,590 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (81, 6, 'Athletics Men''s 20 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (82, 6, 'Athletics Men''s 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (83, 6, 'Athletics Men''s 200 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (84, 6, 'Athletics Men''s 3 mile, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (85, 6, 'Athletics Men''s 3,000 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (86, 6, 'Athletics Men''s 3,000 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (87, 6, 'Athletics Men''s 3,000 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (88, 6, 'Athletics Men''s 3,200 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (89, 6, 'Athletics Men''s 3,500 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (90, 6, 'Athletics Men''s 4 mile, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (91, 6, 'Athletics Men''s 4 x 100 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (92, 6, 'Athletics Men''s 4 x 400 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (93, 6, 'Athletics Men''s 4,000 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (94, 6, 'Athletics Men''s 400 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (95, 6, 'Athletics Men''s 400 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (96, 6, 'Athletics Men''s 5 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (97, 6, 'Athletics Men''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (98, 6, 'Athletics Men''s 5,000 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (99, 6, 'Athletics Men''s 50 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (100, 6, 'Athletics Men''s 56-pound Weight Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (101, 6, 'Athletics Men''s 60 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (102, 6, 'Athletics Men''s 800 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (103, 6, 'Athletics Men''s All-Around Championship');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (104, 6, 'Athletics Men''s Cross-Country, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (105, 6, 'Athletics Men''s Cross-Country, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (106, 6, 'Athletics Men''s Decathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (107, 6, 'Athletics Men''s Discus Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (108, 6, 'Athletics Men''s Discus Throw, Both Hands');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (109, 6, 'Athletics Men''s Discus Throw, Greek Style');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (110, 6, 'Athletics Men''s Hammer Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (111, 6, 'Athletics Men''s High Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (112, 6, 'Athletics Men''s Javelin Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (113, 6, 'Athletics Men''s Javelin Throw, Both Hands');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (114, 6, 'Athletics Men''s Javelin Throw, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (115, 6, 'Athletics Men''s Long Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (116, 6, 'Athletics Men''s Marathon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (117, 6, 'Athletics Men''s Pentathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (118, 6, 'Athletics Men''s Pentathlon (Ancient)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (119, 6, 'Athletics Men''s Pole Vault');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (120, 6, 'Athletics Men''s Shot Put');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (121, 6, 'Athletics Men''s Shot Put, Both Hands');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (122, 6, 'Athletics Men''s Standing High Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (123, 6, 'Athletics Men''s Standing Long Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (124, 6, 'Athletics Men''s Standing Triple Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (125, 6, 'Athletics Men''s Stone Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (126, 6, 'Athletics Men''s Triple Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (127, 6, 'Athletics Women''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (128, 6, 'Athletics Women''s 10 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (129, 6, 'Athletics Women''s 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (130, 6, 'Athletics Women''s 100 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (131, 6, 'Athletics Women''s 100 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (132, 6, 'Athletics Women''s 20 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (133, 6, 'Athletics Women''s 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (134, 6, 'Athletics Women''s 3,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (135, 6, 'Athletics Women''s 3,000 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (136, 6, 'Athletics Women''s 4 x 100 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (137, 6, 'Athletics Women''s 4 x 400 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (138, 6, 'Athletics Women''s 400 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (139, 6, 'Athletics Women''s 400 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (140, 6, 'Athletics Women''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (141, 6, 'Athletics Women''s 80 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (142, 6, 'Athletics Women''s 800 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (143, 6, 'Athletics Women''s Discus Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (144, 6, 'Athletics Women''s Hammer Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (145, 6, 'Athletics Women''s Heptathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (146, 6, 'Athletics Women''s High Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (147, 6, 'Athletics Women''s Javelin Throw');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (148, 6, 'Athletics Women''s Long Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (149, 6, 'Athletics Women''s Marathon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (150, 6, 'Athletics Women''s Pentathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (151, 6, 'Athletics Women''s Pole Vault');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (152, 6, 'Athletics Women''s Shot Put');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (153, 6, 'Athletics Women''s Triple Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (154, 7, 'Badminton Men''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (155, 7, 'Badminton Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (156, 7, 'Badminton Mixed Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (157, 7, 'Badminton Women''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (158, 7, 'Badminton Women''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (159, 8, 'Baseball Men''s Baseball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (160, 9, 'Basketball Men''s Basketball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (161, 9, 'Basketball Women''s Basketball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (162, 10, 'Basque Pelota Men''s Two-Man Teams With Cesta');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (163, 11, 'Beach Volleyball Men''s Beach Volleyball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (164, 11, 'Beach Volleyball Women''s Beach Volleyball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (165, 12, 'Biathlon Men''s 10 kilometres Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (166, 12, 'Biathlon Men''s 12.5 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (167, 12, 'Biathlon Men''s 15 kilometres Mass Start');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (168, 12, 'Biathlon Men''s 20 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (169, 12, 'Biathlon Men''s 4 x 7.5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (170, 12, 'Biathlon Mixed 2 x 6 kilometres and 2 x 7.5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (171, 12, 'Biathlon Women''s 10 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (172, 12, 'Biathlon Women''s 12.5 kilometres Mass Start');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (173, 12, 'Biathlon Women''s 15 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (174, 12, 'Biathlon Women''s 3 x 7.5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (175, 12, 'Biathlon Women''s 4 x 6 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (176, 12, 'Biathlon Women''s 4 x 7.5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (177, 12, 'Biathlon Women''s 7.5 kilometres Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (178, 13, 'Bobsleigh Men''s Four');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (179, 13, 'Bobsleigh Men''s Four/Five');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (180, 13, 'Bobsleigh Men''s Two');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (181, 13, 'Bobsleigh Women''s Two');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (182, 14, 'Boxing Men''s Bantamweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (183, 14, 'Boxing Men''s Featherweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (184, 14, 'Boxing Men''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (185, 14, 'Boxing Men''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (186, 14, 'Boxing Men''s Light-Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (187, 14, 'Boxing Men''s Light-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (188, 14, 'Boxing Men''s Light-Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (189, 14, 'Boxing Men''s Light-Welterweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (190, 14, 'Boxing Men''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (191, 14, 'Boxing Men''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (192, 14, 'Boxing Men''s Super-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (193, 14, 'Boxing Men''s Welterweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (194, 14, 'Boxing Women''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (195, 14, 'Boxing Women''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (196, 14, 'Boxing Women''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (197, 15, 'Canoeing Men''s Canadian Doubles, 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (198, 15, 'Canoeing Men''s Canadian Doubles, 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (199, 15, 'Canoeing Men''s Canadian Doubles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (200, 15, 'Canoeing Men''s Canadian Doubles, Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (201, 15, 'Canoeing Men''s Canadian Singles, 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (202, 15, 'Canoeing Men''s Canadian Singles, 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (203, 15, 'Canoeing Men''s Canadian Singles, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (204, 15, 'Canoeing Men''s Canadian Singles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (205, 15, 'Canoeing Men''s Canadian Singles, Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (206, 15, 'Canoeing Men''s Folding Kayak Doubles, 10 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (207, 15, 'Canoeing Men''s Folding Kayak Singles, 10 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (208, 15, 'Canoeing Men''s Kayak Doubles, 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (209, 15, 'Canoeing Men''s Kayak Doubles, 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (210, 15, 'Canoeing Men''s Kayak Doubles, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (211, 15, 'Canoeing Men''s Kayak Doubles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (212, 15, 'Canoeing Men''s Kayak Fours, 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (213, 15, 'Canoeing Men''s Kayak Relay 4 x 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (214, 15, 'Canoeing Men''s Kayak Singles, 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (215, 15, 'Canoeing Men''s Kayak Singles, 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (216, 15, 'Canoeing Men''s Kayak Singles, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (217, 15, 'Canoeing Men''s Kayak Singles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (218, 15, 'Canoeing Men''s Kayak Singles, Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (219, 15, 'Canoeing Women''s Kayak Doubles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (220, 15, 'Canoeing Women''s Kayak Fours, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (221, 15, 'Canoeing Women''s Kayak Singles, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (222, 15, 'Canoeing Women''s Kayak Singles, 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (223, 15, 'Canoeing Women''s Kayak Singles, Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (224, 16, 'Cricket Men''s Cricket');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (225, 17, 'Croquet Mixed Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (226, 17, 'Croquet Mixed Singles, One Ball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (227, 17, 'Croquet Mixed Singles, Two Balls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (228, 18, 'Cross Country Skiing Men''s 10 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (229, 18, 'Cross Country Skiing Men''s 10/10 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (230, 18, 'Cross Country Skiing Men''s 10/15 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (231, 18, 'Cross Country Skiing Men''s 15 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (232, 18, 'Cross Country Skiing Men''s 18 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (233, 18, 'Cross Country Skiing Men''s 30 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (234, 18, 'Cross Country Skiing Men''s 30 km Skiathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (235, 18, 'Cross Country Skiing Men''s 4 x 10 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (236, 18, 'Cross Country Skiing Men''s 50 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (237, 18, 'Cross Country Skiing Men''s Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (238, 18, 'Cross Country Skiing Men''s Team Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (239, 18, 'Cross Country Skiing Women''s 10 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (240, 18, 'Cross Country Skiing Women''s 15 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (241, 18, 'Cross Country Skiing Women''s 15 km Skiathlon');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (242, 18, 'Cross Country Skiing Women''s 20 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (243, 18, 'Cross Country Skiing Women''s 3 x 5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (244, 18, 'Cross Country Skiing Women''s 30 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (245, 18, 'Cross Country Skiing Women''s 4 x 5 kilometres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (246, 18, 'Cross Country Skiing Women''s 5 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (247, 18, 'Cross Country Skiing Women''s 5/10 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (248, 18, 'Cross Country Skiing Women''s 5/5 kilometres Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (249, 18, 'Cross Country Skiing Women''s Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (250, 18, 'Cross Country Skiing Women''s Team Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (251, 19, 'Curling Men''s Curling');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (252, 19, 'Curling Women''s Curling');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (253, 20, 'Cycling Men''s 1 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (254, 20, 'Cycling Men''s 1,000 metres Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (255, 20, 'Cycling Men''s 1/2 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (256, 20, 'Cycling Men''s 1/3 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (257, 20, 'Cycling Men''s 1/4 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (258, 20, 'Cycling Men''s 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (259, 20, 'Cycling Men''s 100 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (260, 20, 'Cycling Men''s 100 kilometres Team Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (261, 20, 'Cycling Men''s 12-Hours Race');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (262, 20, 'Cycling Men''s 2 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (263, 20, 'Cycling Men''s 20 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (264, 20, 'Cycling Men''s 25 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (265, 20, 'Cycling Men''s 25 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (266, 20, 'Cycling Men''s 333 metres Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (267, 20, 'Cycling Men''s 5 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (268, 20, 'Cycling Men''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (269, 20, 'Cycling Men''s 50 kilometres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (270, 20, 'Cycling Men''s BMX');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (271, 20, 'Cycling Men''s Individual Pursuit, 4,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (272, 20, 'Cycling Men''s Individual Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (273, 20, 'Cycling Men''s Keirin');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (274, 20, 'Cycling Men''s Madison');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (275, 20, 'Cycling Men''s Mountainbike, Cross-Country');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (276, 20, 'Cycling Men''s Omnium');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (277, 20, 'Cycling Men''s Points Race');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (278, 20, 'Cycling Men''s Road Race, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (279, 20, 'Cycling Men''s Road Race, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (280, 20, 'Cycling Men''s Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (281, 20, 'Cycling Men''s Tandem Sprint, 2,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (282, 20, 'Cycling Men''s Team Pursuit, 1,980 yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (283, 20, 'Cycling Men''s Team Pursuit, 4,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (284, 20, 'Cycling Men''s Team Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (285, 20, 'Cycling Women''s 500 metres Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (286, 20, 'Cycling Women''s BMX');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (287, 20, 'Cycling Women''s Individual Pursuit, 3,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (288, 20, 'Cycling Women''s Individual Time Trial');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (289, 20, 'Cycling Women''s Keirin');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (290, 20, 'Cycling Women''s Mountainbike, Cross-Country');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (291, 20, 'Cycling Women''s Omnium');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (292, 20, 'Cycling Women''s Points Race');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (293, 20, 'Cycling Women''s Road Race, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (294, 20, 'Cycling Women''s Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (295, 20, 'Cycling Women''s Team Pursuit');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (296, 20, 'Cycling Women''s Team Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (297, 21, 'Diving Men''s Plain High');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (298, 21, 'Diving Men''s Platform');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (299, 21, 'Diving Men''s Springboard');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (300, 21, 'Diving Men''s Synchronized Platform');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (301, 21, 'Diving Men''s Synchronized Springboard');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (302, 21, 'Diving Women''s Plain High');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (303, 21, 'Diving Women''s Platform');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (304, 21, 'Diving Women''s Springboard');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (305, 21, 'Diving Women''s Synchronized Platform');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (306, 21, 'Diving Women''s Synchronized Springboard');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (307, 22, 'Equestrianism Men''s Dressage, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (308, 22, 'Equestrianism Men''s Dressage, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (309, 22, 'Equestrianism Men''s Jumping, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (310, 22, 'Equestrianism Men''s Jumping, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (311, 22, 'Equestrianism Men''s Three-Day Event, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (312, 22, 'Equestrianism Men''s Three-Day Event, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (313, 22, 'Equestrianism Men''s Vaulting, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (314, 22, 'Equestrianism Men''s Vaulting, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (315, 22, 'Equestrianism Mixed Dressage, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (316, 22, 'Equestrianism Mixed Dressage, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (317, 22, 'Equestrianism Mixed Four-In-Hand Competition');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (318, 22, 'Equestrianism Mixed Hacks And Hunter Combined');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (319, 22, 'Equestrianism Mixed High Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (320, 22, 'Equestrianism Mixed Jumping, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (321, 22, 'Equestrianism Mixed Jumping, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (322, 22, 'Equestrianism Mixed Long Jump');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (323, 22, 'Equestrianism Mixed Three-Day Event, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (324, 22, 'Equestrianism Mixed Three-Day Event, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (325, 23, 'Fencing Men''s Foil, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (326, 23, 'Fencing Men''s Foil, Masters, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (327, 23, 'Fencing Men''s Foil, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (328, 23, 'Fencing Men''s Sabre, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (329, 23, 'Fencing Men''s Sabre, Individual, Three Hits');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (330, 23, 'Fencing Men''s Sabre, Masters, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (331, 23, 'Fencing Men''s Sabre, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (332, 23, 'Fencing Men''s Single Sticks, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (333, 23, 'Fencing Men''s epee, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (334, 23, 'Fencing Men''s epee, Masters and Amateurs, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (335, 23, 'Fencing Men''s epee, Masters, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (336, 23, 'Fencing Men''s epee, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (337, 23, 'Fencing Women''s Foil, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (338, 23, 'Fencing Women''s Foil, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (339, 23, 'Fencing Women''s Sabre, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (340, 23, 'Fencing Women''s Sabre, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (341, 23, 'Fencing Women''s epee, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (342, 23, 'Fencing Women''s epee, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (343, 24, 'Figure Skating Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (344, 24, 'Figure Skating Men''s Special Figures');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (345, 24, 'Figure Skating Mixed Ice Dancing');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (346, 24, 'Figure Skating Mixed Pairs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (347, 24, 'Figure Skating Mixed Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (348, 24, 'Figure Skating Women''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (349, 25, 'Football Men''s Football');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (350, 25, 'Football Women''s Football');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (351, 26, 'Freestyle Skiing Men''s Aerials');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (352, 26, 'Freestyle Skiing Men''s Halfpipe');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (353, 26, 'Freestyle Skiing Men''s Moguls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (354, 26, 'Freestyle Skiing Men''s Ski Cross');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (355, 26, 'Freestyle Skiing Men''s Slopestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (356, 26, 'Freestyle Skiing Women''s Aerials');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (357, 26, 'Freestyle Skiing Women''s Halfpipe');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (358, 26, 'Freestyle Skiing Women''s Moguls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (359, 26, 'Freestyle Skiing Women''s Ski Cross');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (360, 26, 'Freestyle Skiing Women''s Slopestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (361, 27, 'Golf Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (362, 27, 'Golf Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (363, 27, 'Golf Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (364, 28, 'Gymnastics Men''s Club Swinging');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (365, 28, 'Gymnastics Men''s Floor Exercise');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (366, 28, 'Gymnastics Men''s Horizontal Bar');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (367, 28, 'Gymnastics Men''s Horizontal Bar, Teams');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (368, 28, 'Gymnastics Men''s Horse Vault');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (369, 28, 'Gymnastics Men''s Individual All-Around');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (370, 28, 'Gymnastics Men''s Individual All-Around, 4 Events');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (371, 28, 'Gymnastics Men''s Individual All-Around, 5 Events');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (372, 28, 'Gymnastics Men''s Individual All-Around, Apparatus Work');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (373, 28, 'Gymnastics Men''s Individual All-Around, Field Sports');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (374, 28, 'Gymnastics Men''s Parallel Bars');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (375, 28, 'Gymnastics Men''s Parallel Bars, Teams');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (376, 28, 'Gymnastics Men''s Pommelled Horse');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (377, 28, 'Gymnastics Men''s Rings');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (378, 28, 'Gymnastics Men''s Rope Climbing');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (379, 28, 'Gymnastics Men''s Side Horse');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (380, 28, 'Gymnastics Men''s Team All-Around');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (381, 28, 'Gymnastics Men''s Team All-Around, Free System');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (382, 28, 'Gymnastics Men''s Team All-Around, Swedish System');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (383, 28, 'Gymnastics Men''s Tumbling');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (384, 28, 'Gymnastics Women''s Balance Beam');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (385, 28, 'Gymnastics Women''s Floor Exercise');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (386, 28, 'Gymnastics Women''s Horse Vault');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (387, 28, 'Gymnastics Women''s Individual All-Around');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (388, 28, 'Gymnastics Women''s Team All-Around');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (389, 28, 'Gymnastics Women''s Team Portable Apparatus');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (390, 28, 'Gymnastics Women''s Uneven Bars');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (391, 29, 'Handball Men''s Handball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (392, 29, 'Handball Women''s Handball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (393, 30, 'Hockey Men''s Hockey');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (394, 30, 'Hockey Women''s Hockey');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (395, 31, 'Ice Hockey Men''s Ice Hockey');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (396, 31, 'Ice Hockey Women''s Ice Hockey');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (397, 32, 'Jeu De Paume Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (398, 33, 'Judo Men''s Extra-Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (399, 33, 'Judo Men''s Half-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (400, 33, 'Judo Men''s Half-Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (401, 33, 'Judo Men''s Half-Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (402, 33, 'Judo Men''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (403, 33, 'Judo Men''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (404, 33, 'Judo Men''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (405, 33, 'Judo Men''s Open Class');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (406, 33, 'Judo Women''s Extra-Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (407, 33, 'Judo Women''s Half-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (408, 33, 'Judo Women''s Half-Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (409, 33, 'Judo Women''s Half-Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (410, 33, 'Judo Women''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (411, 33, 'Judo Women''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (412, 33, 'Judo Women''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (413, 34, 'Lacrosse Men''s Lacrosse');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (414, 35, 'Luge Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (415, 35, 'Luge Mixed (Men)''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (416, 35, 'Luge Mixed Team Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (417, 35, 'Luge Women''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (418, 36, 'Military Ski Patrol Men''s Military Ski Patrol');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (419, 37, 'Modern Pentathlon Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (420, 37, 'Modern Pentathlon Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (421, 37, 'Modern Pentathlon Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (422, 38, 'Motorboating Mixed A-Class (Open)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (423, 38, 'Motorboating Mixed B-Class (Under 60 Feet)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (424, 38, 'Motorboating Mixed C-Class');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (425, 39, 'Nordic Combined Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (426, 39, 'Nordic Combined Men''s Large Hill / 10 km, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (427, 39, 'Nordic Combined Men''s Normal Hill / 10 km, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (428, 39, 'Nordic Combined Men''s Sprint');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (429, 39, 'Nordic Combined Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (430, 40, 'Polo Men''s Polo');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (431, 41, 'Racquets Men''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (432, 41, 'Racquets Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (433, 42, 'Rhythmic Gymnastics Women''s Group');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (434, 42, 'Rhythmic Gymnastics Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (435, 43, 'Roque Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (436, 44, 'Rowing Men''s 17-Man Naval Rowing Boats');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (437, 44, 'Rowing Men''s 6-Man Naval Rowing Boats');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (438, 44, 'Rowing Men''s Coxed Eights');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (439, 44, 'Rowing Men''s Coxed Fours');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (440, 44, 'Rowing Men''s Coxed Fours, Inriggers');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (441, 44, 'Rowing Men''s Coxed Fours, Outriggers');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (442, 44, 'Rowing Men''s Coxed Pairs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (443, 44, 'Rowing Men''s Coxed Pairs (1 kilometres)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (444, 44, 'Rowing Men''s Coxed Pairs (1 mile)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (445, 44, 'Rowing Men''s Coxless Fours');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (446, 44, 'Rowing Men''s Coxless Pairs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (447, 44, 'Rowing Men''s Double Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (448, 44, 'Rowing Men''s Lightweight Coxless Fours');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (449, 44, 'Rowing Men''s Lightweight Double Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (450, 44, 'Rowing Men''s Quadruple Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (451, 44, 'Rowing Men''s Single Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (452, 44, 'Rowing Women''s Coxed Eights');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (453, 44, 'Rowing Women''s Coxed Fours');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (454, 44, 'Rowing Women''s Coxed Quadruple Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (455, 44, 'Rowing Women''s Coxless Fours');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (456, 44, 'Rowing Women''s Coxless Pairs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (457, 44, 'Rowing Women''s Double Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (458, 44, 'Rowing Women''s Lightweight Double Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (459, 44, 'Rowing Women''s Quadruple Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (460, 44, 'Rowing Women''s Single Sculls');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (461, 45, 'Rugby Men''s Rugby');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (462, 46, 'Rugby Sevens Men''s Rugby Sevens');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (463, 46, 'Rugby Sevens Women''s Rugby Sevens');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (464, 47, 'Sailing Men''s One Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (465, 47, 'Sailing Men''s One Person Heavyweight Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (466, 47, 'Sailing Men''s Skiff');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (467, 47, 'Sailing Men''s Two Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (468, 47, 'Sailing Men''s Two Person Keelboat');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (469, 47, 'Sailing Men''s Windsurfer');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (470, 47, 'Sailing Mixed 0-0.5 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (471, 47, 'Sailing Mixed 0.5-1 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (472, 47, 'Sailing Mixed 1-2 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (473, 47, 'Sailing Mixed 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (474, 47, 'Sailing Mixed 10-20 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (475, 47, 'Sailing Mixed 12 foot');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (476, 47, 'Sailing Mixed 12 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (477, 47, 'Sailing Mixed 18 foot');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (478, 47, 'Sailing Mixed 2-3 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (479, 47, 'Sailing Mixed 20+ Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (480, 47, 'Sailing Mixed 3-10 Ton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (481, 47, 'Sailing Mixed 30 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (482, 47, 'Sailing Mixed 40 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (483, 47, 'Sailing Mixed 5.5 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (484, 47, 'Sailing Mixed 6 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (485, 47, 'Sailing Mixed 6.5 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (486, 47, 'Sailing Mixed 7 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (487, 47, 'Sailing Mixed 8 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (488, 47, 'Sailing Mixed Multihull');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (489, 47, 'Sailing Mixed One Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (490, 47, 'Sailing Mixed Open');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (491, 47, 'Sailing Mixed Skiff');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (492, 47, 'Sailing Mixed Three Person Keelboat');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (493, 47, 'Sailing Mixed Two Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (494, 47, 'Sailing Mixed Two Person Heavyweight Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (495, 47, 'Sailing Mixed Two Person Keelboat');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (496, 47, 'Sailing Mixed Windsurfer');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (497, 47, 'Sailing Women''s One Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (498, 47, 'Sailing Women''s Skiff');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (499, 47, 'Sailing Women''s Three Person Keelboat');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (500, 47, 'Sailing Women''s Two Person Dinghy');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (501, 47, 'Sailing Women''s Windsurfer');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (502, 48, 'Shooting Men''s Air Pistol, 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (503, 48, 'Shooting Men''s Air Rifle, 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (504, 48, 'Shooting Men''s Double Trap');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (505, 48, 'Shooting Men''s Dueling Pistol Au Commandement, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (506, 48, 'Shooting Men''s Dueling Pistol Au Vise 20 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (507, 48, 'Shooting Men''s Dueling Pistol, 30 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (508, 48, 'Shooting Men''s Dueling Pistol, 30 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (509, 48, 'Shooting Men''s Free Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (510, 48, 'Shooting Men''s Free Pistol, 30 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (511, 48, 'Shooting Men''s Free Pistol, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (512, 48, 'Shooting Men''s Free Pistol, 50 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (513, 48, 'Shooting Men''s Free Pistol, 50 yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (514, 48, 'Shooting Men''s Free Pistol, 50 yards, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (515, 48, 'Shooting Men''s Free Rifle, 1,000 Yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (516, 48, 'Shooting Men''s Free Rifle, 400, 600 and 800 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (517, 48, 'Shooting Men''s Free Rifle, Any Position, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (518, 48, 'Shooting Men''s Free Rifle, Kneeling, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (519, 48, 'Shooting Men''s Free Rifle, Prone, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (520, 48, 'Shooting Men''s Free Rifle, Prone, 600 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (521, 48, 'Shooting Men''s Free Rifle, Standing, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (522, 48, 'Shooting Men''s Free Rifle, Three Positions, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (523, 48, 'Shooting Men''s Free Rifle, Three Positions, 300 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (524, 48, 'Shooting Men''s Military Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (525, 48, 'Shooting Men''s Military Pistol, 30 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (526, 48, 'Shooting Men''s Military Pistol, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (527, 48, 'Shooting Men''s Military Revolver, 1873-1874 Gras Model, 20 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (528, 48, 'Shooting Men''s Military Revolver, 20 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (529, 48, 'Shooting Men''s Military Rifle, 1873-1874 Gras Model, Kneeling Or Standing, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (530, 48, 'Shooting Men''s Military Rifle, 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (531, 48, 'Shooting Men''s Military Rifle, 200, 400, 500 and 600 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (532, 48, 'Shooting Men''s Military Rifle, 200/500/600/800/900/1,000 Yards, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (533, 48, 'Shooting Men''s Military Rifle, 300 metres and 600 metres, Prone, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (534, 48, 'Shooting Men''s Military Rifle, Any Position, 600 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (535, 48, 'Shooting Men''s Military Rifle, Kneeling Or Standing, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (536, 48, 'Shooting Men''s Military Rifle, Prone, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (537, 48, 'Shooting Men''s Military Rifle, Prone, 300 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (538, 48, 'Shooting Men''s Military Rifle, Prone, 600 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (539, 48, 'Shooting Men''s Military Rifle, Prone, 600 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (540, 48, 'Shooting Men''s Military Rifle, Standing, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (541, 48, 'Shooting Men''s Military Rifle, Standing, 300 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (542, 48, 'Shooting Men''s Military Rifle, Three Positions, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (543, 48, 'Shooting Men''s Muzzle-Loading Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (544, 48, 'Shooting Men''s Rapid-Fire Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (545, 48, 'Shooting Men''s Running Target, 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (546, 48, 'Shooting Men''s Running Target, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (547, 48, 'Shooting Men''s Running Target, Double Shot');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (548, 48, 'Shooting Men''s Running Target, Double Shot, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (549, 48, 'Shooting Men''s Running Target, Single And Double Shot');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (550, 48, 'Shooting Men''s Running Target, Single Shot');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (551, 48, 'Shooting Men''s Running Target, Single Shot, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (552, 48, 'Shooting Men''s Skeet');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (553, 48, 'Shooting Men''s Small Bore-Rifle, Standing, 50 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (554, 48, 'Shooting Men''s Small-Bore Rifle, 50 and 100 yards, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (555, 48, 'Shooting Men''s Small-Bore Rifle, Any Position, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (556, 48, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (557, 48, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (558, 48, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (559, 48, 'Shooting Men''s Small-Bore Rifle, Moving Target, 25 yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (560, 48, 'Shooting Men''s Small-Bore Rifle, Prone, 50 and 100 yards');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (561, 48, 'Shooting Men''s Small-Bore Rifle, Prone, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (562, 48, 'Shooting Men''s Small-Bore Rifle, Prone, 50 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (563, 48, 'Shooting Men''s Small-Bore Rifle, Standing, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (564, 48, 'Shooting Men''s Small-Bore Rifle, Three Positions, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (565, 48, 'Shooting Men''s Trap');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (566, 48, 'Shooting Men''s Trap, Double Shot, 14 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (567, 48, 'Shooting Men''s Trap, Single Shot, 16 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (568, 48, 'Shooting Men''s Trap, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (569, 48, 'Shooting Men''s Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (570, 48, 'Shooting Mixed Free Pistol, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (571, 48, 'Shooting Mixed Free Rifle, Three Positions, 300 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (572, 48, 'Shooting Mixed Rapid-Fire Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (573, 48, 'Shooting Mixed Running Target, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (574, 48, 'Shooting Mixed Skeet');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (575, 48, 'Shooting Mixed Small-Bore Rifle, Prone, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (576, 48, 'Shooting Mixed Small-Bore Rifle, Three Positions, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (577, 48, 'Shooting Mixed Trap');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (578, 48, 'Shooting Women''s Air Pistol, 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (579, 48, 'Shooting Women''s Air Rifle, 10 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (580, 48, 'Shooting Women''s Double Trap');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (581, 48, 'Shooting Women''s Skeet');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (582, 48, 'Shooting Women''s Small-Bore Rifle, Three Positions, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (583, 48, 'Shooting Women''s Sporting Pistol, 25 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (584, 48, 'Shooting Women''s Trap');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (585, 49, 'Short Track Speed Skating Men''s 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (586, 49, 'Short Track Speed Skating Men''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (587, 49, 'Short Track Speed Skating Men''s 5,000 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (588, 49, 'Short Track Speed Skating Men''s 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (589, 49, 'Short Track Speed Skating Women''s 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (590, 49, 'Short Track Speed Skating Women''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (591, 49, 'Short Track Speed Skating Women''s 3,000 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (592, 49, 'Short Track Speed Skating Women''s 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (593, 50, 'Skeleton Men''s Skeleton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (594, 50, 'Skeleton Women''s Skeleton');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (595, 51, 'Ski Jumping Men''s Large Hill, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (596, 51, 'Ski Jumping Men''s Large Hill, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (597, 51, 'Ski Jumping Men''s Normal Hill, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (598, 51, 'Ski Jumping Women''s Normal Hill, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (599, 52, 'Snowboarding Men''s Boardercross');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (600, 52, 'Snowboarding Men''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (601, 52, 'Snowboarding Men''s Halfpipe');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (602, 52, 'Snowboarding Men''s Parallel Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (603, 52, 'Snowboarding Men''s Parallel Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (604, 52, 'Snowboarding Men''s Slopestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (605, 52, 'Snowboarding Women''s Boardercross');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (606, 52, 'Snowboarding Women''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (607, 52, 'Snowboarding Women''s Halfpipe');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (608, 52, 'Snowboarding Women''s Parallel Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (609, 52, 'Snowboarding Women''s Parallel Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (610, 52, 'Snowboarding Women''s Slopestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (611, 53, 'Softball Women''s Softball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (612, 54, 'Speed Skating Men''s 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (613, 54, 'Speed Skating Men''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (614, 54, 'Speed Skating Men''s 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (615, 54, 'Speed Skating Men''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (616, 54, 'Speed Skating Men''s 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (617, 54, 'Speed Skating Men''s Allround');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (618, 54, 'Speed Skating Men''s Team Pursuit (8 laps)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (619, 54, 'Speed Skating Women''s 1,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (620, 54, 'Speed Skating Women''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (621, 54, 'Speed Skating Women''s 3,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (622, 54, 'Speed Skating Women''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (623, 54, 'Speed Skating Women''s 500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (624, 54, 'Speed Skating Women''s Team Pursuit (6 laps)');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (625, 55, 'Swimming Men''s 1,000 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (626, 55, 'Swimming Men''s 1,200 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (627, 55, 'Swimming Men''s 1,500 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (628, 55, 'Swimming Men''s 10 kilometres Open Water');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (629, 55, 'Swimming Men''s 100 Yard Backstroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (630, 55, 'Swimming Men''s 100 metres Backstroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (631, 55, 'Swimming Men''s 100 metres Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (632, 55, 'Swimming Men''s 100 metres Butterfly');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (633, 55, 'Swimming Men''s 100 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (634, 55, 'Swimming Men''s 100 metres Freestyle For Sailors');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (635, 55, 'Swimming Men''s 100 yard Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (636, 55, 'Swimming Men''s 200 metres Backstroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (637, 55, 'Swimming Men''s 200 metres Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (638, 55, 'Swimming Men''s 200 metres Butterfly');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (639, 55, 'Swimming Men''s 200 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (640, 55, 'Swimming Men''s 200 metres Individual Medley');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (641, 55, 'Swimming Men''s 200 metres Obstacle Course');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (642, 55, 'Swimming Men''s 200 metres Team Swimming');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (643, 55, 'Swimming Men''s 220 yard Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (644, 55, 'Swimming Men''s 4 x 100 metres Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (645, 55, 'Swimming Men''s 4 x 100 metres Medley Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (646, 55, 'Swimming Men''s 4 x 200 metres Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (647, 55, 'Swimming Men''s 4 x 250 metres Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (648, 55, 'Swimming Men''s 4 x 50 Yard Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (649, 55, 'Swimming Men''s 4,000 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (650, 55, 'Swimming Men''s 400 metres Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (651, 55, 'Swimming Men''s 400 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (652, 55, 'Swimming Men''s 400 metres Individual Medley');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (653, 55, 'Swimming Men''s 440 Yard Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (654, 55, 'Swimming Men''s 440 yard Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (655, 55, 'Swimming Men''s 50 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (656, 55, 'Swimming Men''s 50 yard Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (657, 55, 'Swimming Men''s 500 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (658, 55, 'Swimming Men''s 880 yard Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (659, 55, 'Swimming Men''s One Mile Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (660, 55, 'Swimming Men''s Plunge For Distance');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (661, 55, 'Swimming Men''s Underwater Swimming');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (662, 55, 'Swimming Women''s 10 kilometres Open Water');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (663, 55, 'Swimming Women''s 100 metres Backstroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (664, 55, 'Swimming Women''s 100 metres Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (665, 55, 'Swimming Women''s 100 metres Butterfly');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (666, 55, 'Swimming Women''s 100 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (667, 55, 'Swimming Women''s 200 metres Backstroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (668, 55, 'Swimming Women''s 200 metres Breaststroke');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (669, 55, 'Swimming Women''s 200 metres Butterfly');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (670, 55, 'Swimming Women''s 200 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (671, 55, 'Swimming Women''s 200 metres Individual Medley');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (672, 55, 'Swimming Women''s 300 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (673, 55, 'Swimming Women''s 4 x 100 metres Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (674, 55, 'Swimming Women''s 4 x 100 metres Medley Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (675, 55, 'Swimming Women''s 4 x 200 metres Freestyle Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (676, 55, 'Swimming Women''s 400 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (677, 55, 'Swimming Women''s 400 metres Individual Medley');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (678, 55, 'Swimming Women''s 50 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (679, 55, 'Swimming Women''s 800 metres Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (680, 56, 'Synchronized Swimming Women''s Duet');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (681, 56, 'Synchronized Swimming Women''s Solo');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (682, 56, 'Synchronized Swimming Women''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (683, 57, 'Table Tennis Men''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (684, 57, 'Table Tennis Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (685, 57, 'Table Tennis Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (686, 57, 'Table Tennis Women''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (687, 57, 'Table Tennis Women''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (688, 57, 'Table Tennis Women''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (689, 58, 'Taekwondo Men''s Featherweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (690, 58, 'Taekwondo Men''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (691, 58, 'Taekwondo Men''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (692, 58, 'Taekwondo Men''s Welterweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (693, 58, 'Taekwondo Women''s Featherweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (694, 58, 'Taekwondo Women''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (695, 58, 'Taekwondo Women''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (696, 58, 'Taekwondo Women''s Welterweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (697, 59, 'Tennis Men''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (698, 59, 'Tennis Men''s Doubles, Covered Courts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (699, 59, 'Tennis Men''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (700, 59, 'Tennis Men''s Singles, Covered Courts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (701, 59, 'Tennis Mixed Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (702, 59, 'Tennis Mixed Doubles, Covered Courts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (703, 59, 'Tennis Women''s Doubles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (704, 59, 'Tennis Women''s Singles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (705, 59, 'Tennis Women''s Singles, Covered Courts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (706, 60, 'Trampolining Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (707, 60, 'Trampolining Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (708, 61, 'Triathlon Men''s Olympic Distance');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (709, 61, 'Triathlon Women''s Olympic Distance');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (710, 62, 'Tug-Of-War Men''s Tug-Of-War');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (711, 63, 'Volleyball Men''s Volleyball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (712, 63, 'Volleyball Women''s Volleyball');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (713, 64, 'Water Polo Men''s Water Polo');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (714, 64, 'Water Polo Women''s Water Polo');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (715, 65, 'Weightlifting Men''s All-Around Dumbbell Contest');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (716, 65, 'Weightlifting Men''s Bantamweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (717, 65, 'Weightlifting Men''s Featherweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (718, 65, 'Weightlifting Men''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (719, 65, 'Weightlifting Men''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (720, 65, 'Weightlifting Men''s Heavyweight I');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (721, 65, 'Weightlifting Men''s Heavyweight II');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (722, 65, 'Weightlifting Men''s Light-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (723, 65, 'Weightlifting Men''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (724, 65, 'Weightlifting Men''s Middle-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (725, 65, 'Weightlifting Men''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (726, 65, 'Weightlifting Men''s Super-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (727, 65, 'Weightlifting Men''s Unlimited, One Hand');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (728, 65, 'Weightlifting Men''s Unlimited, Two Hands');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (729, 65, 'Weightlifting Women''s Featherweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (730, 65, 'Weightlifting Women''s Flyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (731, 65, 'Weightlifting Women''s Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (732, 65, 'Weightlifting Women''s Light-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (733, 65, 'Weightlifting Women''s Lightweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (734, 65, 'Weightlifting Women''s Middleweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (735, 65, 'Weightlifting Women''s Super-Heavyweight');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (736, 66, 'Wrestling Men''s All-Around, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (737, 66, 'Wrestling Men''s Bantamweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (738, 66, 'Wrestling Men''s Bantamweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (739, 66, 'Wrestling Men''s Featherweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (740, 66, 'Wrestling Men''s Featherweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (741, 66, 'Wrestling Men''s Flyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (742, 66, 'Wrestling Men''s Flyweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (743, 66, 'Wrestling Men''s Heavyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (744, 66, 'Wrestling Men''s Heavyweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (745, 66, 'Wrestling Men''s Light-Flyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (746, 66, 'Wrestling Men''s Light-Flyweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (747, 66, 'Wrestling Men''s Light-Heavyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (748, 66, 'Wrestling Men''s Light-Heavyweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (749, 66, 'Wrestling Men''s Lightweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (750, 66, 'Wrestling Men''s Lightweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (751, 66, 'Wrestling Men''s Middleweight A, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (752, 66, 'Wrestling Men''s Middleweight B, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (753, 66, 'Wrestling Men''s Middleweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (754, 66, 'Wrestling Men''s Middleweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (755, 66, 'Wrestling Men''s Super-Heavyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (756, 66, 'Wrestling Men''s Super-Heavyweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (757, 66, 'Wrestling Men''s Unlimited Class, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (758, 66, 'Wrestling Men''s Welterweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (759, 66, 'Wrestling Men''s Welterweight, Greco-Roman');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (760, 66, 'Wrestling Women''s Featherweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (761, 66, 'Wrestling Women''s Flyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (762, 66, 'Wrestling Women''s Heavyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (763, 66, 'Wrestling Women''s Light-Heavyweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (764, 66, 'Wrestling Women''s Lightweight, Freestyle');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (765, 66, 'Wrestling Women''s Middleweight, Freestyle');

COMMIT;
