INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (1, '1896 Summer', 1896, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (2, '1900 Summer', 1900, 'Summer', 'Paris');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (3, '1904 Summer', 1904, 'Summer', 'St. Louis');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (4, '1906 Summer', 1906, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (5, '1908 Summer', 1908, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (6, '1912 Summer', 1912, 'Summer', 'Stockholm');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (7, '1920 Summer', 1920, 'Summer', 'Antwerpen');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (8, '1924 Summer', 1924, 'Summer', 'Paris');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (9, '1924 Winter', 1924, 'Winter', 'Chamonix');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (10, '1928 Summer', 1928, 'Summer', 'Amsterdam');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (11, '1928 Winter', 1928, 'Winter', 'Sankt Moritz');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (12, '1932 Winter', 1932, 'Winter', 'Lake Placid');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (13, '1932 Summer', 1932, 'Summer', 'Los Angeles');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (14, '1936 Summer', 1936, 'Summer', 'Berlin');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (15, '1936 Winter', 1936, 'Winter', 'Garmisch-Partenkirchen');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (16, '1948 Summer', 1948, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (17, '1948 Winter', 1948, 'Winter', 'Sankt Moritz');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (18, '1952 Summer', 1952, 'Summer', 'Helsinki');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (19, '1952 Winter', 1952, 'Winter', 'Oslo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (20, '1956 Winter', 1956, 'Winter', 'Cortina d''Ampezzo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (21, '1956 Summer', 1956, 'Summer', 'Melbourne');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (22, '1956 Summer', 1956, 'Summer', 'Stockholm');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (23, '1960 Winter', 1960, 'Winter', 'Squaw Valley');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (24, '1960 Summer', 1960, 'Summer', 'Roma');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (25, '1964 Summer', 1964, 'Summer', 'Tokyo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (26, '1964 Winter', 1964, 'Winter', 'Innsbruck');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (27, '1968 Summer', 1968, 'Summer', 'Mexico City');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (28, '1968 Winter', 1968, 'Winter', 'Grenoble');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (29, '1972 Winter', 1972, 'Winter', 'Sapporo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (30, '1972 Summer', 1972, 'Summer', 'Munich');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (31, '1976 Summer', 1976, 'Summer', 'Montreal');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (32, '1976 Winter', 1976, 'Winter', 'Innsbruck');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (33, '1980 Summer', 1980, 'Summer', 'Moskva');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (34, '1980 Winter', 1980, 'Winter', 'Lake Placid');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (35, '1984 Winter', 1984, 'Winter', 'Sarajevo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (36, '1984 Summer', 1984, 'Summer', 'Los Angeles');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (37, '1988 Winter', 1988, 'Winter', 'Calgary');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (38, '1988 Summer', 1988, 'Summer', 'Seoul');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (39, '1992 Summer', 1992, 'Summer', 'Barcelona');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (40, '1992 Winter', 1992, 'Winter', 'Albertville');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (41, '1994 Winter', 1994, 'Winter', 'Lillehammer');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (42, '1996 Summer', 1996, 'Summer', 'Atlanta');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (43, '1998 Winter', 1998, 'Winter', 'Nagano');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (44, '2000 Summer', 2000, 'Summer', 'Sydney');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (45, '2002 Winter', 2002, 'Winter', 'Salt Lake City');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (46, '2004 Summer', 2004, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (47, '2006 Winter', 2006, 'Winter', 'Torino');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (48, '2008 Summer', 2008, 'Summer', 'Beijing');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (49, '2010 Winter', 2010, 'Winter', 'Vancouver');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (50, '2012 Summer', 2012, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (51, '2014 Winter', 2014, 'Winter', 'Sochi');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (52, '2016 Summer', 2016, 'Summer', 'Rio de Janeiro');

COMMIT;
