SHOW CON_NAME;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER OLY_REF CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE USER OLY_REF IDENTIFIED BY oly_ref
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO OLY_REF;
