CREATE TABLE OLY_REF.SPORTS (
    sport_id   NUMBER(10)    PRIMARY KEY,
    sport_name VARCHAR2(100) NOT NULL
);

CREATE TABLE OLY_REF.EVENTS (
    event_id   NUMBER(10)    PRIMARY KEY,
    sport_id   NUMBER(10)    NOT NULL,
    event_name VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_EVENTS_SPORT
        FOREIGN KEY (sport_id) REFERENCES OLY_REF.SPORTS(sport_id)
);

CREATE TABLE OLY_REF.GAMES (
    game_id    NUMBER(10)    PRIMARY KEY,
    games_name VARCHAR2(50)  NOT NULL,
    year       NUMBER(4)     NOT NULL,
    season     VARCHAR2(10)  NOT NULL,
    city       VARCHAR2(100) NOT NULL
);

CREATE TABLE OLY_REF.COUNTRIES (
    noc    VARCHAR2(10)  PRIMARY KEY,
    region VARCHAR2(200) NOT NULL,
    notes  VARCHAR2(500)
);

GRANT SELECT ON OLY_REF.SPORTS    TO FDBO;
GRANT SELECT ON OLY_REF.EVENTS    TO FDBO;
GRANT SELECT ON OLY_REF.GAMES     TO FDBO;
GRANT SELECT ON OLY_REF.COUNTRIES TO FDBO;

SELECT table_name, num_rows
FROM all_tables
WHERE owner = 'OLY_REF'
ORDER BY table_name;
