BEGIN
  EXECUTE IMMEDIATE 'DROP USER OLY_REF CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE USER OLY_REF IDENTIFIED BY "Oracle_1234#"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO OLY_REF;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER FDBO CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE USER FDBO IDENTIFIED BY "Oracle_1234#"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CONNECT, RESOURCE TO FDBO;
GRANT CREATE VIEW TO FDBO;
GRANT CREATE DATABASE LINK TO FDBO;

SELECT username, account_status, created
FROM dba_users
WHERE username IN ('FDBO', 'OLY_REF')
ORDER BY username;
