INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (1, 1, 'Aeronautics Mixed Aeronautics');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (2, 2, 'Alpine Skiing Men''s Combined');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (3, 2, 'Alpine Skiing Men''s Downhill');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (4, 2, 'Alpine Skiing Men''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (5, 2, 'Alpine Skiing Men''s Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (6, 2, 'Alpine Skiing Men''s Super G');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (7, 2, 'Alpine Skiing Women''s Combined');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (8, 2, 'Alpine Skiing Women''s Downhill');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (9, 2, 'Alpine Skiing Women''s Giant Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (10, 2, 'Alpine Skiing Women''s Slalom');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (11, 2, 'Alpine Skiing Women''s Super G');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (12, 3, 'Alpinism Mixed Alpinism');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (13, 4, 'Archery Men''s Au Chapelet, 33 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (14, 4, 'Archery Men''s Au Chapelet, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (15, 4, 'Archery Men''s Au Cordon Dore, 33 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (16, 4, 'Archery Men''s Au Cordon Dore, 50 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (17, 4, 'Archery Men''s Championnat Du Monde');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (18, 4, 'Archery Men''s Continental Style');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (19, 4, 'Archery Men''s Double American Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (20, 4, 'Archery Men''s Double York Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (21, 4, 'Archery Men''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (22, 4, 'Archery Men''s Pole Archery, Large Birds, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (23, 4, 'Archery Men''s Pole Archery, Large Birds, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (24, 4, 'Archery Men''s Pole Archery, Small Birds, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (25, 4, 'Archery Men''s Pole Archery, Small Birds, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (26, 4, 'Archery Men''s Sur La Perche a La Herse');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (27, 4, 'Archery Men''s Sur La Perche a La Pyramide');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (28, 4, 'Archery Men''s Target Archery, 28 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (29, 4, 'Archery Men''s Target Archery, 28 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (30, 4, 'Archery Men''s Target Archery, 33 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (31, 4, 'Archery Men''s Target Archery, 33 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (32, 4, 'Archery Men''s Target Archery, 50 metres, Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (33, 4, 'Archery Men''s Target Archery, 50 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (34, 4, 'Archery Men''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (35, 4, 'Archery Men''s Team Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (36, 4, 'Archery Men''s Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (37, 4, 'Archery Women''s Double Columbia Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (38, 4, 'Archery Women''s Double National Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (39, 4, 'Archery Women''s Individual');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (40, 4, 'Archery Women''s Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (41, 4, 'Archery Women''s Team Round');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (42, 5, 'Art Competitions Mixed Architecture');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (43, 5, 'Art Competitions Mixed Architecture, Architectural Designs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (44, 5, 'Art Competitions Mixed Architecture, Designs For Town Planning');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (45, 5, 'Art Competitions Mixed Architecture, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (46, 5, 'Art Competitions Mixed Literature');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (47, 5, 'Art Competitions Mixed Literature, Dramatic Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (48, 5, 'Art Competitions Mixed Literature, Epic Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (49, 5, 'Art Competitions Mixed Literature, Lyric Works');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (50, 5, 'Art Competitions Mixed Literature, Unknown Event');
COMMIT;

INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (51, 5, 'Art Competitions Mixed Music');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (52, 5, 'Art Competitions Mixed Music, Compositions For Orchestra');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (53, 5, 'Art Competitions Mixed Music, Compositions For Solo Or Chorus');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (54, 5, 'Art Competitions Mixed Music, Instrumental And Chamber');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (55, 5, 'Art Competitions Mixed Music, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (56, 5, 'Art Competitions Mixed Music, Vocals');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (57, 5, 'Art Competitions Mixed Painting');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (58, 5, 'Art Competitions Mixed Painting, Applied Arts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (59, 5, 'Art Competitions Mixed Painting, Drawings And Water Colors');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (60, 5, 'Art Competitions Mixed Painting, Graphic Arts');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (61, 5, 'Art Competitions Mixed Painting, Paintings');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (62, 5, 'Art Competitions Mixed Painting, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (63, 5, 'Art Competitions Mixed Sculpturing');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (64, 5, 'Art Competitions Mixed Sculpturing, Medals');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (65, 5, 'Art Competitions Mixed Sculpturing, Medals And Plaques');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (66, 5, 'Art Competitions Mixed Sculpturing, Medals And Reliefs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (67, 5, 'Art Competitions Mixed Sculpturing, Reliefs');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (68, 5, 'Art Competitions Mixed Sculpturing, Statues');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (69, 5, 'Art Competitions Mixed Sculpturing, Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (70, 5, 'Art Competitions Mixed Unknown Event');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (71, 6, 'Athletics Men''s 1,500 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (72, 6, 'Athletics Men''s 1,500 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (73, 6, 'Athletics Men''s 1,600 metres Medley Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (74, 6, 'Athletics Men''s 10 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (75, 6, 'Athletics Men''s 10 mile Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (76, 6, 'Athletics Men''s 10,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (77, 6, 'Athletics Men''s 100 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (78, 6, 'Athletics Men''s 110 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (79, 6, 'Athletics Men''s 2,500 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (80, 6, 'Athletics Men''s 2,590 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (81, 6, 'Athletics Men''s 20 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (82, 6, 'Athletics Men''s 200 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (83, 6, 'Athletics Men''s 200 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (84, 6, 'Athletics Men''s 3 mile, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (85, 6, 'Athletics Men''s 3,000 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (86, 6, 'Athletics Men''s 3,000 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (87, 6, 'Athletics Men''s 3,000 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (88, 6, 'Athletics Men''s 3,200 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (89, 6, 'Athletics Men''s 3,500 metres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (90, 6, 'Athletics Men''s 4 mile, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (91, 6, 'Athletics Men''s 4 x 100 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (92, 6, 'Athletics Men''s 4 x 400 metres Relay');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (93, 6, 'Athletics Men''s 4,000 metres Steeplechase');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (94, 6, 'Athletics Men''s 400 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (95, 6, 'Athletics Men''s 400 metres Hurdles');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (96, 6, 'Athletics Men''s 5 mile');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (97, 6, 'Athletics Men''s 5,000 metres');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (98, 6, 'Athletics Men''s 5,000 metres, Team');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (99, 6, 'Athletics Men''s 50 kilometres Walk');
INSERT INTO OLY_REF.EVENTS (event_id, sport_id, event_name) VALUES (100, 6, 'Athletics Men''s 56-pound Weight Throw');
COMMIT;

SELECT 'EVENTS' AS tabel, COUNT(*) AS nr FROM OLY_REF.EVENTS;
