INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (1, 'Aeronautics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (2, 'Alpine Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (3, 'Alpinism');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (4, 'Archery');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (5, 'Art Competitions');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (6, 'Athletics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (7, 'Badminton');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (8, 'Baseball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (9, 'Basketball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (10, 'Basque Pelota');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (11, 'Beach Volleyball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (12, 'Biathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (13, 'Bobsleigh');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (14, 'Boxing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (15, 'Canoeing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (16, 'Cricket');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (17, 'Croquet');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (18, 'Cross Country Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (19, 'Curling');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (20, 'Cycling');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (21, 'Diving');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (22, 'Equestrianism');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (23, 'Fencing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (24, 'Figure Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (25, 'Football');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (26, 'Freestyle Skiing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (27, 'Golf');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (28, 'Gymnastics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (29, 'Handball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (30, 'Hockey');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (31, 'Ice Hockey');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (32, 'Jeu De Paume');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (33, 'Judo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (34, 'Lacrosse');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (35, 'Luge');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (36, 'Military Ski Patrol');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (37, 'Modern Pentathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (38, 'Motorboating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (39, 'Nordic Combined');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (40, 'Polo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (41, 'Racquets');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (42, 'Rhythmic Gymnastics');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (43, 'Roque');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (44, 'Rowing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (45, 'Rugby');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (46, 'Rugby Sevens');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (47, 'Sailing');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (48, 'Shooting');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (49, 'Short Track Speed Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (50, 'Skeleton');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (51, 'Ski Jumping');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (52, 'Snowboarding');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (53, 'Softball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (54, 'Speed Skating');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (55, 'Swimming');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (56, 'Synchronized Swimming');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (57, 'Table Tennis');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (58, 'Taekwondo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (59, 'Tennis');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (60, 'Trampolining');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (61, 'Triathlon');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (62, 'Tug-Of-War');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (63, 'Volleyball');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (64, 'Water Polo');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (65, 'Weightlifting');
INSERT INTO OLY_REF.SPORTS (sport_id, sport_name) VALUES (66, 'Wrestling');

COMMIT;

INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (1, '1896 Summer', 1896, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (2, '1900 Summer', 1900, 'Summer', 'Paris');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (3, '1904 Summer', 1904, 'Summer', 'St. Louis');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (4, '1906 Summer', 1906, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (5, '1908 Summer', 1908, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (6, '1912 Summer', 1912, 'Summer', 'Stockholm');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (7, '1920 Summer', 1920, 'Summer', 'Antwerpen');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (8, '1924 Summer', 1924, 'Summer', 'Paris');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (9, '1924 Winter', 1924, 'Winter', 'Chamonix');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (10, '1928 Summer', 1928, 'Summer', 'Amsterdam');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (11, '1928 Winter', 1928, 'Winter', 'Sankt Moritz');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (12, '1932 Winter', 1932, 'Winter', 'Lake Placid');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (13, '1932 Summer', 1932, 'Summer', 'Los Angeles');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (14, '1936 Summer', 1936, 'Summer', 'Berlin');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (15, '1936 Winter', 1936, 'Winter', 'Garmisch-Partenkirchen');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (16, '1948 Summer', 1948, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (17, '1948 Winter', 1948, 'Winter', 'Sankt Moritz');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (18, '1952 Summer', 1952, 'Summer', 'Helsinki');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (19, '1952 Winter', 1952, 'Winter', 'Oslo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (20, '1956 Winter', 1956, 'Winter', 'Cortina d''Ampezzo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (21, '1956 Summer', 1956, 'Summer', 'Melbourne');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (22, '1956 Summer', 1956, 'Summer', 'Stockholm');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (23, '1960 Winter', 1960, 'Winter', 'Squaw Valley');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (24, '1960 Summer', 1960, 'Summer', 'Roma');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (25, '1964 Summer', 1964, 'Summer', 'Tokyo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (26, '1964 Winter', 1964, 'Winter', 'Innsbruck');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (27, '1968 Summer', 1968, 'Summer', 'Mexico City');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (28, '1968 Winter', 1968, 'Winter', 'Grenoble');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (29, '1972 Winter', 1972, 'Winter', 'Sapporo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (30, '1972 Summer', 1972, 'Summer', 'Munich');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (31, '1976 Summer', 1976, 'Summer', 'Montreal');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (32, '1976 Winter', 1976, 'Winter', 'Innsbruck');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (33, '1980 Summer', 1980, 'Summer', 'Moskva');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (34, '1980 Winter', 1980, 'Winter', 'Lake Placid');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (35, '1984 Winter', 1984, 'Winter', 'Sarajevo');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (36, '1984 Summer', 1984, 'Summer', 'Los Angeles');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (37, '1988 Winter', 1988, 'Winter', 'Calgary');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (38, '1988 Summer', 1988, 'Summer', 'Seoul');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (39, '1992 Summer', 1992, 'Summer', 'Barcelona');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (40, '1992 Winter', 1992, 'Winter', 'Albertville');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (41, '1994 Winter', 1994, 'Winter', 'Lillehammer');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (42, '1996 Summer', 1996, 'Summer', 'Atlanta');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (43, '1998 Winter', 1998, 'Winter', 'Nagano');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (44, '2000 Summer', 2000, 'Summer', 'Sydney');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (45, '2002 Winter', 2002, 'Winter', 'Salt Lake City');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (46, '2004 Summer', 2004, 'Summer', 'Athina');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (47, '2006 Winter', 2006, 'Winter', 'Torino');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (48, '2008 Summer', 2008, 'Summer', 'Beijing');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (49, '2010 Winter', 2010, 'Winter', 'Vancouver');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (50, '2012 Summer', 2012, 'Summer', 'London');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (51, '2014 Winter', 2014, 'Winter', 'Sochi');
INSERT INTO OLY_REF.GAMES (game_id, games_name, year, season, city) VALUES (52, '2016 Summer', 2016, 'Summer', 'Rio de Janeiro');

COMMIT;

INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AFG', 'Afghanistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AHO', 'Curacao', 'Netherlands Antilles');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ALB', 'Albania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ALG', 'Algeria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AND', 'Andorra', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANG', 'Angola', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANT', 'Antigua', 'Antigua and Barbuda');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ANZ', 'Australia', 'Australasia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARG', 'Argentina', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARM', 'Armenia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ARU', 'Aruba', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ASA', 'American Samoa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AUS', 'Australia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AUT', 'Austria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('AZE', 'Azerbaijan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAH', 'Bahamas', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAN', 'Bangladesh', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BAR', 'Barbados', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BDI', 'Burundi', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BEL', 'Belgium', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BEN', 'Benin', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BER', 'Bermuda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BHU', 'Bhutan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BIH', 'Bosnia and Herzegovina', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BIZ', 'Belize', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BLR', 'Belarus', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOH', 'Czech Republic', 'Bohemia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOL', 'Boliva', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BOT', 'Botswana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRA', 'Brazil', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRN', 'Bahrain', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BRU', 'Brunei', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BUL', 'Bulgaria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('BUR', 'Burkina Faso', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAF', 'Central African Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAM', 'Cambodia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAN', 'Canada', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CAY', 'Cayman Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CGO', 'Republic of Congo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHA', 'Chad', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHI', 'Chile', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CHN', 'China', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CIV', 'Ivory Coast', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CMR', 'Cameroon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COD', 'Democratic Republic of the Congo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COK', 'Cook Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COL', 'Colombia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('COM', 'Comoros', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CPV', 'Cape Verde', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRC', 'Costa Rica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRO', 'Croatia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CRT', 'Greece', 'Crete');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CUB', 'Cuba', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CYP', 'Cyprus', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('CZE', 'Czech Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DEN', 'Denmark', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DJI', 'Djibouti', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DMA', 'Dominica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('DOM', 'Dominican Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ECU', 'Ecuador', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EGY', 'Egypt', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ERI', 'Eritrea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ESA', 'El Salvador', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ESP', 'Spain', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EST', 'Estonia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ETH', 'Ethiopia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('EUN', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FIJ', 'Fiji', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FIN', 'Finland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FRA', 'France', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FRG', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('FSM', 'Micronesia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GAB', 'Gabon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GAM', 'Gambia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GBR', 'UK', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GBS', 'Guinea-Bissau', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GDR', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GEO', 'Georgia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GEQ', 'Equatorial Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GER', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GHA', 'Ghana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GRE', 'Greece', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GRN', 'Grenada', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUA', 'Guatemala', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUI', 'Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUM', 'Guam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('GUY', 'Guyana', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HAI', 'Haiti', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HKG', 'China', 'Hong Kong');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HON', 'Honduras', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('HUN', 'Hungary', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('INA', 'Indonesia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IND', 'India', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IOA', 'Individual Olympic Athletes', 'Individual Olympic Athletes');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRI', 'Iran', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRL', 'Ireland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IRQ', 'Iraq', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISL', 'Iceland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISR', 'Israel', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ISV', 'Virgin Islands, US', 'Virgin Islands');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ITA', 'Italy', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('IVB', 'Virgin Islands, British', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JAM', 'Jamaica', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JOR', 'Jordan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('JPN', 'Japan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KAZ', 'Kazakhstan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KEN', 'Kenya', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KGZ', 'Kyrgyzstan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KIR', 'Kiribati', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KOR', 'South Korea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KOS', 'Kosovo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KSA', 'Saudi Arabia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('KUW', 'Kuwait', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LAO', 'Laos', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LAT', 'Latvia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LBA', 'Libya', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LBR', 'Liberia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LCA', 'Saint Lucia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LES', 'Lesotho', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LIB', 'Lebanon', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LIE', 'Liechtenstein', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LTU', 'Lithuania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('LUX', 'Luxembourg', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAD', 'Madagascar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAL', 'Malaysia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAR', 'Morocco', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAS', 'Malaysia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MAW', 'Malawi', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MDA', 'Moldova', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MDV', 'Maldives', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MEX', 'Mexico', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MGL', 'Mongolia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MHL', 'Marshall Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MKD', 'Macedonia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MLI', 'Mali', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MLT', 'Malta', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MNE', 'Montenegro', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MON', 'Monaco', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MOZ', 'Mozambique', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MRI', 'Mauritius', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MTN', 'Mauritania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('MYA', 'Myanmar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NAM', 'Namibia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NBO', 'Malaysia', 'North Borneo');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NCA', 'Nicaragua', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NED', 'Netherlands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NEP', 'Nepal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NFL', 'Canada', 'Newfoundland');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NGR', 'Nigeria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NIG', 'Niger', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NOR', 'Norway', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NRU', 'Nauru', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('NZL', 'New Zealand', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('OMA', 'Oman', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAK', 'Pakistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAN', 'Panama', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PAR', 'Paraguay', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PER', 'Peru', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PHI', 'Philippines', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PLE', 'Palestine', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PLW', 'Palau', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PNG', 'Papua New Guinea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('POL', 'Poland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('POR', 'Portugal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PRK', 'North Korea', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('PUR', 'Puerto Rico', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('QAT', 'Qatar', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RHO', 'Zimbabwe', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ROT', 'Refugee Olympic Team', 'Refugee Olympic Team');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ROU', 'Romania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RSA', 'South Africa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RUS', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('RWA', 'Rwanda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SAA', 'Germany', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SAM', 'Samoa', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SCG', 'Serbia', 'Serbia and Montenegro');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SEN', 'Senegal', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SEY', 'Seychelles', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SIN', 'Singapore', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SKN', 'Saint Kitts', 'Turks and Caicos Islands');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SLE', 'Sierra Leone', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SLO', 'Slovenia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SMR', 'San Marino', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SOL', 'Solomon Islands', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SOM', 'Somalia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SRB', 'Serbia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SRI', 'Sri Lanka', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SSD', 'South Sudan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('STP', 'Sao Tome and Principe', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUD', 'Sudan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUI', 'Switzerland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SUR', 'Suriname', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SVK', 'Slovakia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SWE', 'Sweden', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SWZ', 'Swaziland', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('SYR', 'Syria', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TAN', 'Tanzania', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TCH', 'Czech Republic', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TGA', 'Tonga', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('THA', 'Thailand', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TJK', 'Tajikistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TKM', 'Turkmenistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TLS', 'Timor-Leste', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TOG', 'Togo', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TPE', 'Taiwan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TTO', 'Trinidad', 'Trinidad and Tobago');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUN', 'Tunisia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUR', 'Turkey', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('TUV', 'Tuvalu', 'Tuvalu');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UAE', 'United Arab Emirates', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UAR', 'Syria', 'United Arab Republic');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UGA', 'Uganda', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UKR', 'Ukraine', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UNK', 'Unknown', 'Unknown');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('URS', 'Russia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('URU', 'Uruguay', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('USA', 'USA', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('UZB', 'Uzbekistan', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VAN', 'Vanuatu', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VEN', 'Venezuela', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VIE', 'Vietnam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VIN', 'Saint Vincent', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('VNM', 'Vietnam', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('WIF', 'Trinidad', 'West Indies Federation');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YAR', 'Yemen', 'North Yemen');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YEM', 'Yemen', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YMD', 'Yemen', 'South Yemen');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('YUG', 'Serbia', 'Yugoslavia');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ZAM', 'Zambia', '');
INSERT INTO OLY_REF.COUNTRIES (noc, region, notes) VALUES ('ZIM', 'Zimbabwe', '');

COMMIT;

SELECT 'SPORTS' AS tabel, COUNT(*) AS nr FROM OLY_REF.SPORTS
UNION ALL
SELECT 'GAMES', COUNT(*) FROM OLY_REF.GAMES
UNION ALL
SELECT 'COUNTRIES', COUNT(*) FROM OLY_REF.COUNTRIES;
